#!/bin/bash
set -e

cd $(dirname $0)/..

rm -rf build/stage
mkdir -p build/stage
mkdir -p dist
pushd build/stage

BASE=$(echo ../*/output/target/)

mkdir -p usr/bin

cp $BASE/bin/busybox usr/bin
cp $BASE/usr/sbin/xtables-multi usr/bin/iptables
cp $BASE/usr/bin/xz usr/bin/xz

ln -s busybox usr/bin/ps
ln -s busybox usr/bin/modprobe
ln -s busybox usr/bin/mount
ln -s busybox usr/bin/echo

tar cvzf ../../dist/artifacts/os-initrd-base-${1}.tar.gz .
